# Generated by Django 3.0.5 on 2024-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('unit', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
